name: CLI Tool Issue
description: Report an issue with the LightMesh CLI Tool
title: "[CLI]: "
labels: ["cli"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report for the LightMesh CLI Tool!
        
  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - label: Bug
        - label: Feature Request
        - label: Command Error
        - label: Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g. macOS 14.1, Windows 11
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g. v18.0.0
    validations:
      required: true

  - type: input
    id: cli-version
    attributes:
      label: CLI Version
      description: What version of the LightMesh CLI are you using?
      placeholder: Output of `lightmesh --version`
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command you ran
      placeholder: |
        ```bash
        lightmesh <command> [options]
        ```
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If applicable, paste the error output here
      render: shell

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here 