name: IPAM Application Issue
description: Report an issue with the LightMesh IPAM Application
title: "[IPAM]: "
labels: ["ipam"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report for the LightMesh IPAM Application!
        
  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - label: Bug
        - label: Feature Request
        - label: Performance Issue
        - label: Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: e.g. Chrome 120, Firefox 121
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g. macOS 14.1, Windows 11
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: IPAM Version
      description: If applicable, what version of IPAM are you using?
      placeholder: e.g. 2.1.0

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here 